### ISSUE TITLE
Writing to disk continuously

### ISSUE THREAD

**Issue by hantuzun** [gettyimages/marathon_exporter#9]
Thanks for the exporter <3 Here's our issue with it though:

Our server dedicated to monitoring has had its disk filled up. Inspecting the case, I've found out that our `marathon_exporter`'s  container has filled all the free space with time. Killing it freed 26GB of disk space.

```
$ sudo du -hDaxd1 /var/lib/docker/containers | sort -h | tail -n10
44K    /var/lib/docker/containers/971355c1c830626e3cf201fff29bad51a71773cace1f797f56afcb62a560b73e
148K    /var/lib/docker/containers/d521ffbbefd2b97621f2013a578ff41e253051e120dbe739e1e18199e3eb0e41
280K    /var/lib/docker/containers/c5b88e49187f226589789b85ea5fa30a6573a604eb626a4474ccd25eecbcd70b
4.7M    /var/lib/docker/containers/9bd646fbcc13b11dcb92b96ec3602e6ac2ecd9388dddac71574baa40bad5bd16
7.5M    /var/lib/docker/containers/03babecae56c7f33b825defe612e9807367e1dc5b9da904a63c64f8d32378657
11M    /var/lib/docker/containers/5e735c2bc7653069389078f685b62e745a12ad2a35bb422dc8a4bfb692a7d83f
39M    /var/lib/docker/containers/fec1c7a6cf68bf5d060e07e5ac71f40a54a38586f95d197d4c6ca9c8b8b1f07e
109M    /var/lib/docker/containers/8c00d8ba884d753da4c58b510439b014d393033701a321383bee5112ee447505
27G    /var/lib/docker/containers
27G    /var/lib/docker/containers/9525a738ddd2fd4720b71262b166f145df02faebfb9d69482e898c87af586a06
```

```sh
$ docker ps
CONTAINER ID        IMAGE                                                                                                        COMMAND                  CREATED             STATUS              PORTS               NAMES
9525a738ddd2        gettyimages/marathon_exporter@sha256:e5fff2905753cdf79902afbd9110115f0d309c1ea8f4f68e4c442b9da8c82fe3        "/marathon_exporte..."   2 months ago        Up 2 months         9088/tcp            tetracorder_marathon_exporter.1.9f4dd97tk7n2lrgzglao5p8lb

.
.
.
```

Here's the service definition of our `marathon_exporter`:

```yml
  marathon_exporter:
    image: gettyimages/marathon_exporter:v1.5.0-RC1
    command: -marathon.uri http://${MESOS_MASTER_LB_IP}/service/marathon -web.listen-address :9088
    deploy:
      replicas: 1
      restart_policy:
        condition: any
```
